name: Hello workflow

on:
  push:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "やあ！"

      - name: Show datetime
        run: echo "実行日時:$(date)"

      - name: Show branch ref
        run: echo "ブランチ名 (github.ref):${{ github.ref }}"

      - name: Show actor
        run: echo "実行者:${{ github.actor }}"
